# Generated by Django 5.0.6 on 2026-09-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('RETIREMENT', 'Retirement'), ('CHILD_EDUCATION', 'Child Education'), ('HOME_PURCHASE', 'Home Purchase'), ('WEALTH_CREATION', 'Wealth Creation'), ('EMERGENCY_FUND', 'Emergency Fund'), ('VACATION', 'Vacation / Travel'), ('WEDDING', 'Wedding'), ('CAR_PURCHASE', 'Car Purchase'), ('OTHER', 'Other')], default='WEALTH_CREATION', max_length=25)),
                ('custom_name', models.CharField(blank=True, help_text='Custom name when goal_type is OTHER.', max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target amount in ₹.', max_digits=16)),
                ('target_years', models.PositiveIntegerField(help_text='Number of years to reach this goal.')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 = highest priority.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text='Investor age (18–70).')),
                ('monthly_income', models.DecimalField(decimal_places=2, help_text='Monthly income in ₹.', max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, help_text='Monthly expenses in ₹.', max_digits=12)),
                ('existing_investments', models.DecimalField(decimal_places=2, default=0, help_text='Total current investment value in ₹.', max_digits=14)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=0, help_text='Emergency fund already set aside in ₹.', max_digits=14)),
                ('income_range', models.CharField(choices=[('BELOW_3L', 'Below ₹3 LPA'), ('RANGE_3L_6L', '₹3–6 LPA'), ('RANGE_6L_10L', '₹6–10 LPA'), ('RANGE_10L_20L', '₹10–20 LPA'), ('RANGE_20L_50L', '₹20–50 LPA'), ('ABOVE_50L', 'Above ₹50 LPA')], default='RANGE_3L_6L', max_length=20)),
                ('experience', models.CharField(choices=[('BEGINNER', 'Beginner (0–1 years)'), ('INTERMEDIATE', 'Intermediate (1–3 years)'), ('EXPERIENCED', 'Experienced (3–7 years)'), ('EXPERT', 'Expert (7+ years)')], default='BEGINNER', max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE_CONSERVATIVE', 'Moderate Conservative'), ('MODERATE', 'Moderate'), ('MODERATE_AGGRESSIVE', 'Moderate Aggressive'), ('AGGRESSIVE', 'Aggressive')], default='MODERATE', max_length=25)),
                ('risk_score', models.IntegerField(default=50, help_text='0–100 risk score from questionnaire.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'verbose_name_plural': 'Investor Profiles',
            },
        ),
        migrations.CreateModel(
            name='MoneyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=150)),
                ('equity_pct', models.DecimalField(decimal_places=2, default=60, help_text='Equity allocation %.', max_digits=5)),
                ('debt_pct', models.DecimalField(decimal_places=2, default=25, help_text='Debt / Fixed Income allocation %.', max_digits=5)),
                ('gold_pct', models.DecimalField(decimal_places=2, default=10, help_text='Gold allocation %.', max_digits=5)),
                ('cash_pct', models.DecimalField(decimal_places=2, default=5, help_text='Cash / Liquid allocation %.', max_digits=5)),
                ('total_monthly_sip', models.DecimalField(decimal_places=2, default=0, help_text='Recommended total monthly SIP in ₹.', max_digits=12)),
                ('projected_corpus_5y', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('projected_corpus_10y', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('projected_corpus_15y', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('projected_corpus_20y', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sip_returns_pct', models.DecimalField(decimal_places=2, default=12, help_text='Assumed annual return % for SIP projections.', max_digits=5)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='investments.investorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_sip_needed', models.DecimalField(decimal_places=2, help_text='Monthly SIP needed for this goal.', max_digits=12)),
                ('projected_amount', models.DecimalField(decimal_places=2, help_text='Projected amount at goal deadline.', max_digits=18)),
                ('shortfall', models.DecimalField(decimal_places=2, default=0, help_text='Positive = surplus, negative = shortfall.', max_digits=18)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='investments.investmentgoal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_projections', to='investments.moneyplan')),
            ],
            options={
                'verbose_name': 'Goal Projection',
                'verbose_name_plural': 'Goal Projections',
            },
        ),
        migrations.CreateModel(
            name='SIPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='E.g. Large Cap, Mid Cap, Liquid Fund.', max_length=50)),
                ('sub_category', models.CharField(blank=True, help_text='E.g. Index Fund, Corporate Bond.', max_length=50)),
                ('allocation_pct', models.DecimalField(decimal_places=2, help_text='% of total SIP.', max_digits=5)),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Monthly SIP amount in ₹.', max_digits=12)),
                ('suggested_return_pct', models.DecimalField(decimal_places=2, default=12, help_text='Assumed annual return for this category.', max_digits=5)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_entries', to='investments.moneyplan')),
            ],
            options={
                'ordering': ['-allocation_pct'],
            },
        ),
    ]
