# Generated by Django 5.0.6 on 2026-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='age',
            field=models.PositiveIntegerField(default=30, help_text='Investor age (18–70).'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly expenses in ₹.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly income in ₹.', max_digits=12),
        ),
    ]
