# Generated by Django 5.0.6 on 2026-09-08 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LISTED', 'Recently Listed')], default='UPCOMING', max_length=20)),
                ('industry', models.CharField(blank=True, default='', max_length=150)),
                ('exchange', models.CharField(blank=True, default='NSE / BSE', max_length=50)),
                ('price_band_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_band_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('issue_size_crore', models.DecimalField(blank=True, decimal_places=2, help_text='Issue size in ₹ crore, if available.', max_digits=14, null=True)),
                ('lot_size', models.PositiveIntegerField(blank=True, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('allotment_date', models.DateField(blank=True, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('gmp', models.DecimalField(blank=True, decimal_places=2, help_text='Unofficial Grey Market Premium. It may change and does not guarantee listing performance.', max_digits=12, null=True)),
                ('total_subscription', models.DecimalField(blank=True, decimal_places=2, help_text='Overall subscription in times, for example 2.50.', max_digits=12, null=True)),
                ('qib_subscription', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nii_subscription', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_subscription', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue_crore', models.DecimalField(blank=True, decimal_places=2, help_text='Latest available annual revenue in ₹ crore.', max_digits=16, null=True)),
                ('profit_crore', models.DecimalField(blank=True, decimal_places=2, help_text='Latest available annual profit in ₹ crore.', max_digits=16, null=True)),
                ('debt_crore', models.DecimalField(blank=True, decimal_places=2, help_text='Latest available debt in ₹ crore.', max_digits=16, null=True)),
                ('fresh_issue_crore', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('offer_for_sale_crore', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('promoter_information', models.TextField(blank=True, default='')),
                ('business_summary', models.TextField(blank=True, default='')),
                ('risk_factors', models.TextField(blank=True, default='', help_text='Important risks from official documents, if available.')),
                ('official_source_url', models.URLField(blank=True, default='', help_text='Official exchange, registrar, or offer-document URL.')),
                ('source_name', models.CharField(blank=True, default='', help_text='Example: NSE, BSE, registrar, or authorized provider.', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this IPO from normal users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['status', 'open_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundamental_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gmp_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subscription_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valuation_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='Higher score means lower relative risk in this educational model.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('classification', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('HIGH_RISK', 'High Risk'), ('NEEDS_MORE_RESEARCH', 'Needs More Research'), ('INSUFFICIENT_DATA', 'Insufficient Data')], default='INSUFFICIENT_DATA', max_length=30)),
                ('assessment', models.TextField(blank=True, default='')),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('things_to_check', models.JSONField(default=list)),
                ('analysis_snapshot', models.JSONField(default=dict, help_text='IPO data supplied to the educational agent.')),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ipo.ipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPO Analysis',
                'verbose_name_plural': 'IPO Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
