# Generated by Django 5.0.6 on 2026-09-08 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('STOCK_SEARCH', 'Stock Search'), ('STOCK_ANALYSIS', 'Stock Analysis'), ('STOCK_COMPARISON', 'Stock Comparison'), ('IPO_SEARCH', 'IPO Search'), ('IPO_ANALYSIS', 'IPO Analysis'), ('INVESTMENT_PLAN', 'Investment Plan'), ('EDUCATION_VIEW', 'Education View')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='Optional ID of a linked analysis object.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Analysis Log',
                'verbose_name_plural': 'AI Analysis Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
