# Generated by Django 5.0.6 on 2026-09-08 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('last_quote', models.JSONField(blank=True, default=dict)),
                ('last_fundamentals', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_overview', models.TextField(blank=True)),
                ('fundamental_score', models.IntegerField(blank=True, null=True)),
                ('technical_score', models.IntegerField(blank=True, null=True)),
                ('growth_score', models.IntegerField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('important_factors', models.JSONField(blank=True, default=list)),
                ('conclusion', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('STRONG', 'Strong'), ('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('CAUTION', 'Caution'), ('HIGH RISK', 'High Risk')], default='NEUTRAL', max_length=20)),
                ('source', models.CharField(default='rule_based', help_text="'ai' or 'rule_based' — which engine produced this analysis.", max_length=20)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='stocks.stock')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
